/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vistas;

import Logica.Carta;
import Logica.Color;
import java.awt.Font;
import javax.swing.JLabel;
import javax.swing.JOptionPane;


/**
 *
 * @author Usuario
 */
public class ElegirColorFrame extends javax.swing.JFrame {

    private Color wildColor = null;
    Boolean permitir = false;
    PopUp popUp;
    
    public ElegirColorFrame(PopUp pop){
        initComponents();
        popUp = pop;
    }
    
    public ElegirColorFrame() {
        initComponents();
    }
    
    public Color colorElegido(Carta carta){
        if(carta.getColor() == Color.Wild){
            this.setVisible(true);
            this.setResizable(false);
            this.setBounds(100,150,600,700);
        }
        return carta.getColor();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnRojo = new javax.swing.JButton();
        btnAzul = new javax.swing.JButton();
        btnVerde = new javax.swing.JButton();
        btnAmarillo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Selecciona el color del comodín");

        btnRojo.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        btnRojo.setText("Rojo");
        btnRojo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRojoActionPerformed(evt);
            }
        });

        btnAzul.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        btnAzul.setText("Azul");
        btnAzul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAzulActionPerformed(evt);
            }
        });

        btnVerde.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        btnVerde.setText("Verde");
        btnVerde.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerdeActionPerformed(evt);
            }
        });

        btnAmarillo.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        btnAmarillo.setText("Amarillo");
        btnAmarillo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAmarilloActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(182, 182, 182)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnAzul, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnRojo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnVerde, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnAmarillo, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE))))
                .addContainerGap(88, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel1)
                .addGap(44, 44, 44)
                .addComponent(btnRojo, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(btnAzul, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(btnVerde, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(btnAmarillo, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRojoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRojoActionPerformed
        wildColor = Color.Red;
        JLabel mensaje =new JLabel("El comodín es Rojo!");
        mensaje.setFont(new Font("Arial", Font.BOLD,48));
        JOptionPane.showMessageDialog(null,mensaje);
        permitir = true;
        this.dispose();
        popUp.colorDeclarado = Color.Red;
        popUp.etapaJuego.setPidName(popUp.juego.GetJugadorActual());
        popUp.etapaJuego.setButtonIcons();
        popUp.btnUltimaCartaTirada.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/PNGs/small/" + popUp.juego.GetImagenCartaSuperior())));
        popUp.juego.SetColorCarta(Color.Red);
        popUp.dispose();
    }//GEN-LAST:event_btnRojoActionPerformed

    private void btnAzulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAzulActionPerformed
        wildColor = Color.Blue;
        JLabel mensaje =new JLabel("El comodín es Azul!");
        mensaje.setFont(new Font("Arial", Font.BOLD,48));
        JOptionPane.showMessageDialog(null,mensaje);
        permitir = true;
        this.dispose();
        popUp.colorDeclarado = Color.Blue;
        popUp.etapaJuego.setPidName(popUp.juego.GetJugadorActual());
        popUp.etapaJuego.setButtonIcons();
        popUp.btnUltimaCartaTirada.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/PNGs/small/" + popUp.juego.GetImagenCartaSuperior())));
        popUp.juego.SetColorCarta(Color.Blue);
        popUp.dispose();
    }//GEN-LAST:event_btnAzulActionPerformed

    private void btnVerdeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerdeActionPerformed
        wildColor = Color.Green;
        JLabel mensaje =new JLabel("El comodín es Verde!");
        mensaje.setFont(new Font("Arial", Font.BOLD,48));
        JOptionPane.showMessageDialog(null,mensaje);
        permitir = true;
        this.dispose();
        popUp.colorDeclarado = Color.Green;
        popUp.etapaJuego.setPidName(popUp.juego.GetJugadorActual());
        popUp.etapaJuego.setButtonIcons();
        popUp.btnUltimaCartaTirada.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/PNGs/small/" + popUp.juego.GetImagenCartaSuperior())));
        popUp.juego.SetColorCarta(Color.Green);
        popUp.dispose();
    }//GEN-LAST:event_btnVerdeActionPerformed

    private void btnAmarilloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAmarilloActionPerformed
        wildColor = Color.Yellow;
        JLabel mensaje =new JLabel("El comodín es Amarillo!");
        mensaje.setFont(new Font("Arial", Font.BOLD,48));
        JOptionPane.showMessageDialog(null,mensaje);
        permitir = true;
        this.dispose();
        popUp.colorDeclarado = Color.Yellow;
        popUp.etapaJuego.setPidName(popUp.juego.GetJugadorActual());
        popUp.etapaJuego.setButtonIcons();
        popUp.btnUltimaCartaTirada.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/PNGs/small/" + popUp.juego.GetImagenCartaSuperior())));
        popUp.juego.SetColorCarta(Color.Yellow);
        popUp.dispose();
    }//GEN-LAST:event_btnAmarilloActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ElegirColorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ElegirColorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ElegirColorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ElegirColorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ElegirColorFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAmarillo;
    private javax.swing.JButton btnAzul;
    private javax.swing.JButton btnRojo;
    private javax.swing.JButton btnVerde;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
